---
title: "Faith Phase 2 work"
author: "Faith Wong"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# reading in csv file from GitHub to R as "delays" dataframe
delays <- read.csv("https://raw.githubusercontent.com/nekalik/STAT-335-Project/main/Airline_Delay_Cause.csv")
```

```{r}
# adding column for date
delays$date = as.Date(paste(delays$year, delays$month, 1, sep = "-"))
str(delays)
```

```{r}
# moving date column to the first position
library(dplyr)
delays <- delays %>%
  select(date, everything())
str(delays)
```

```{r}
# delays_num contains only numerical data (categorical variables removed)
delays_num <- subset(delays, select = -c(year,month,carrier,carrier_name,airport,airport_name))
str(delays_num)
# finding mean of all columns for each day
delays_sum <- aggregate(.~date, delays_num,mean)
head(delays_sum)
# subset dataframe to only contain data before Covid (January 2017-December 2019)
delays_sum <- delays_sum[delays_sum$date<"2020-01-01",]
tail(delays_sum)
```

# Trying things from Shan's code

```{r}
corrdel <- delays_sum[,3:8] # number of flights delayed
str(corrdel)

# looking at the makeup of number of flights delayed (due to what reason) - is this statistically sound??
library(corrplot)
corrplot(cor(corrdel))
```



